/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'alias' : IDL.Text,
  'blocked' : IDL.Bool,
  'role' : UserRole,
  'registeredAt' : Time,
});
export const Post = IDL.Record({
  'id' : IDL.Text,
  'categoryId' : IDL.Text,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'body' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'pinned' : IDL.Bool,
  'authorPrincipal' : IDL.Principal,
});
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'createCategory' : IDL.Func([IDL.Text], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'editPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyLikedPosts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listPosts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Post)], ['query']),
  'listPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'pinPost' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'register' : IDL.Func([IDL.Text], [], []),
  'setRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'alias' : IDL.Text,
    'blocked' : IDL.Bool,
    'role' : UserRole,
    'registeredAt' : Time,
  });
  const Post = IDL.Record({
    'id' : IDL.Text,
    'categoryId' : IDL.Text,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'body' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'pinned' : IDL.Bool,
    'authorPrincipal' : IDL.Principal,
  });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'createCategory' : IDL.Func([IDL.Text], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'editPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyLikedPosts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getPost' : IDL.Func([IDL.Text], [IDL.Opt(Post)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listPosts' : IDL.Func([IDL.Opt(IDL.Text)], [IDL.Vec(Post)], ['query']),
    'listPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(Post)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'pinPost' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'register' : IDL.Func([IDL.Text], [], []),
    'setRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };