/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export interface Post {
  'id' : string,
  'categoryId' : string,
  'title' : string,
  'likeCount' : bigint,
  'body' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'pinned' : boolean,
  'authorPrincipal' : Principal,
}
export type Time = bigint;
export interface UserProfile {
  'alias' : string,
  'blocked' : boolean,
  'role' : UserRole,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createPost' : ActorMethod<[string, string, string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'editPost' : ActorMethod<[string, string, string, string], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyLikedPosts' : ActorMethod<[], Array<string>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getUser' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listPosts' : ActorMethod<[[] | [string]], Array<Post>>,
  'listPostsByAuthor' : ActorMethod<[string], Array<Post>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'pinPost' : ActorMethod<[string, boolean], undefined>,
  'register' : ActorMethod<[string], undefined>,
  'setRole' : ActorMethod<[Principal, UserRole], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];