/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Category {
  'id' : string,
  'name' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export interface Comment {
  'id' : string,
  'likeCount' : bigint,
  'body' : string,
  'createdAt' : Time,
  'parentId' : [] | [string],
  'authorPrincipal' : Principal,
  'postId' : string,
}
export interface MediaFile {
  'id' : bigint,
  'commentId' : [] | [bigint],
  'ownerId' : Principal,
  'blobKey' : string,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'uploadedAt' : bigint,
  'postId' : [] | [bigint],
}
export type NotificationEvent = { 'NewComment' : null } |
  { 'NewReply' : null } |
  { 'NewMedia' : null };
export interface Notification {
  'id' : bigint,
  'recipientPrincipal' : Principal,
  'postId' : string,
  'triggerPrincipal' : Principal,
  'event' : NotificationEvent,
  'createdAt' : Time,
  'read' : boolean,
}
export interface Post {
  'id' : string,
  'categoryId' : string,
  'title' : string,
  'likeCount' : bigint,
  'body' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'pinned' : boolean,
  'authorPrincipal' : Principal,
}
export interface SearchResult {
  'comments' : Array<Comment>,
  'posts' : Array<Post>,
}
export type Time = bigint;
export interface UserProfile {
  'alias' : string,
  'blocked' : boolean,
  'role' : UserRole,
  'registeredAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithPrincipal {
  'principal' : Principal,
  'profile' : UserProfile,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'createCategory' : ActorMethod<[string], undefined>,
  'createComment' : ActorMethod<[string, string, [] | [string]], undefined>,
  'createPost' : ActorMethod<[string, string, string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'getHiddenCategoryIds' : ActorMethod<[], Array<string>>,
  'toggleCategoryHidden' : ActorMethod<[string, boolean], undefined>,
  'addUserToCategoryAllowedList' : ActorMethod<[string, Principal], undefined>,
  'removeUserFromCategoryAllowedList' : ActorMethod<[string, Principal], undefined>,
  'getCategoryAllowedUsers' : ActorMethod<[string], Array<Principal>>,
  'deleteComment' : ActorMethod<[string], undefined>,
  'deleteMedia' : ActorMethod<[bigint], undefined>,
  'deleteMyAccount' : ActorMethod<[], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'editComment' : ActorMethod<[string, string], undefined>,
  'editPost' : ActorMethod<[string, string, string, string], undefined>,
  'getAllMedia' : ActorMethod<[], Array<MediaFile>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMediaForComment' : ActorMethod<[bigint], Array<MediaFile>>,
  'getMediaForPost' : ActorMethod<[bigint], Array<MediaFile>>,
  'getMyLikedComments' : ActorMethod<[], Array<string>>,
  'getMyLikedPosts' : ActorMethod<[], Array<string>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getPost' : ActorMethod<[string], [] | [Post]>,
  'getUser' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeComment' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'listCategories' : ActorMethod<[], Array<Category>>,
  'listComments' : ActorMethod<[string], Array<Comment>>,
  'listPosts' : ActorMethod<[[] | [string]], Array<Post>>,
  'listPostsByAuthor' : ActorMethod<[string], Array<Post>>,
  'listUsers' : ActorMethod<[], Array<UserProfile>>,
  'listUsersWithPrincipal' : ActorMethod<[], Array<UserWithPrincipal>>,
  'pinPost' : ActorMethod<[string, boolean], undefined>,
  'register' : ActorMethod<[string], undefined>,
  'search' : ActorMethod<[string], SearchResult>,
  'setRole' : ActorMethod<[Principal, UserRole], undefined>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'uploadMedia' : ActorMethod<
    [[] | [bigint], [] | [bigint], string, string, bigint, string],
    bigint
  >,
  'followUser' : ActorMethod<[Principal], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'followPost' : ActorMethod<[string], undefined>,
  'unfollowPost' : ActorMethod<[string], undefined>,
  'getFollowedUsers' : ActorMethod<[], Array<Principal>>,
  'getFollowedUsersPosts' : ActorMethod<[], Array<Post>>,
  'getFollowedPosts' : ActorMethod<[], Array<string>>,
  'isFollowingUser' : ActorMethod<[Principal], boolean>,
  'isFollowingPost' : ActorMethod<[string], boolean>,
  'getPostFollowerCount' : ActorMethod<[string], bigint>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'deleteNotification' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
