/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Category {
    id: string;
    name: string;
    createdAt: Time;
    createdBy: Principal;
}
export interface SearchResult {
    comments: Array<Comment>;
    posts: Array<Post>;
}
export interface MediaFile {
    id: bigint;
    commentId?: bigint;
    ownerId: Principal;
    blobKey: string;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    uploadedAt: bigint;
    postId?: bigint;
}
export type Time = bigint;
export interface Comment {
    id: string;
    likeCount: bigint;
    body: string;
    createdAt: Time;
    parentId?: string;
    authorPrincipal: Principal;
    postId: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface UserWithPrincipal {
    principal: Principal;
    profile: UserProfile;
}
export interface Post {
    id: string;
    categoryId: string;
    title: string;
    likeCount: bigint;
    body: string;
    createdAt: Time;
    updatedAt: Time;
    pinned: boolean;
    authorPrincipal: Principal;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    alias: string;
    blocked: boolean;
    role: UserRole;
    registeredAt: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockUser(user: Principal): Promise<void>;
    createCategory(name: string): Promise<void>;
    createComment(postId: string, body: string, parentId: string | null): Promise<void>;
    createPost(title: string, body: string, categoryId: string): Promise<void>;
    deleteCategory(id: string): Promise<void>;
    deleteComment(commentId: string): Promise<void>;
    deleteMedia(mediaId: bigint): Promise<void>;
    deleteMyAccount(): Promise<void>;
    deletePost(postId: string): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    editComment(commentId: string, body: string): Promise<void>;
    editPost(postId: string, title: string, body: string, categoryId: string): Promise<void>;
    getAllMedia(): Promise<Array<MediaFile>>;
    getCallerUserRole(): Promise<UserRole>;
    getMediaForComment(commentId: bigint): Promise<Array<MediaFile>>;
    getMediaForPost(postId: bigint): Promise<Array<MediaFile>>;
    getMyLikedComments(): Promise<Array<string>>;
    getMyLikedPosts(): Promise<Array<string>>;
    getMyProfile(): Promise<UserProfile | null>;
    getPost(postId: string): Promise<Post | null>;
    getUser(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    likeComment(commentId: string): Promise<void>;
    likePost(postId: string): Promise<void>;
    listCategories(): Promise<Array<Category>>;
    listComments(postId: string): Promise<Array<Comment>>;
    listPosts(categoryId: string | null): Promise<Array<Post>>;
    listPostsByAuthor(alias: string): Promise<Array<Post>>;
    listUsers(): Promise<Array<UserProfile>>;
    listUsersWithPrincipal(): Promise<Array<UserWithPrincipal>>;
    pinPost(postId: string, pinned: boolean): Promise<void>;
    register(alias: string): Promise<void>;
    search(searchQuery: string): Promise<SearchResult>;
    setRole(user: Principal, role: UserRole): Promise<void>;
    unblockUser(user: Principal): Promise<void>;
    uploadMedia(postId: bigint | null, commentId: bigint | null, fileType: string, fileName: string, fileSize: bigint, blobKey: string): Promise<bigint>;
}
import type { Comment as _Comment, MediaFile as _MediaFile, Post as _Post, SearchResult as _SearchResult, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserWithPrincipal as _UserWithPrincipal, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0);
            return result;
        }
    }
    async createCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0);
            return result;
        }
    }
    async createComment(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createComment(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createComment(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createPost(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteMedia(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMedia(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMedia(arg0);
            return result;
        }
    }
    async deleteMyAccount(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyAccount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyAccount();
            return result;
        }
    }
    async deletePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async editComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editComment(arg0, arg1);
            return result;
        }
    }
    async editPost(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editPost(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editPost(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getAllMedia(): Promise<Array<MediaFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMedia();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMedia();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaForComment(arg0: bigint): Promise<Array<MediaFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaForComment(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaForComment(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMediaForPost(arg0: bigint): Promise<Array<MediaFile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaForPost(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaForPost(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLikedComments(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLikedComments();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLikedComments();
            return result;
        }
    }
    async getMyLikedPosts(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLikedPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLikedPosts();
            return result;
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPost(arg0: string): Promise<Post | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPost(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPost(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likeComment(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likeComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeComment(arg0);
            return result;
        }
    }
    async likePost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listComments(arg0: string): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listComments(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listComments(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPosts(arg0: string | null): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPosts(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPosts(to_candid_opt_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async listPostsByAuthor(arg0: string): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPostsByAuthor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPostsByAuthor(arg0);
            return result;
        }
    }
    async listUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersWithPrincipal(): Promise<Array<UserWithPrincipal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersWithPrincipal();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersWithPrincipal();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async pinPost(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinPost(arg0, arg1);
            return result;
        }
    }
    async register(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0);
            return result;
        }
    }
    async search(arg0: string): Promise<SearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.search(arg0);
                return from_candid_SearchResult_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.search(arg0);
            return from_candid_SearchResult_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async setRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async unblockUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0);
            return result;
        }
    }
    async uploadMedia(arg0: bigint | null, arg1: bigint | null, arg2: string, arg3: string, arg4: bigint, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadMedia(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadMedia(to_candid_opt_n30(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_Comment_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Comment): Comment {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MediaFile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaFile): MediaFile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SearchResult_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SearchResult): SearchResult {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserWithPrincipal_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWithPrincipal): UserWithPrincipal {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Post]): Post | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    commentId: [] | [bigint];
    ownerId: Principal;
    blobKey: string;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    uploadedAt: bigint;
    postId: [] | [bigint];
}): {
    id: bigint;
    commentId?: bigint;
    ownerId: Principal;
    blobKey: string;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    uploadedAt: bigint;
    postId?: bigint;
} {
    return {
        id: value.id,
        commentId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.commentId)),
        ownerId: value.ownerId,
        blobKey: value.blobKey,
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileType: value.fileType,
        uploadedAt: value.uploadedAt,
        postId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.postId))
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alias: string;
    blocked: boolean;
    role: _UserRole;
    registeredAt: _Time;
}): {
    alias: string;
    blocked: boolean;
    role: UserRole;
    registeredAt: Time;
} {
    return {
        alias: value.alias,
        blocked: value.blocked,
        role: from_candid_UserRole_n14(_uploadFile, _downloadFile, value.role),
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    likeCount: bigint;
    body: string;
    createdAt: _Time;
    parentId: [] | [string];
    authorPrincipal: Principal;
    postId: string;
}): {
    id: string;
    likeCount: bigint;
    body: string;
    createdAt: Time;
    parentId?: string;
    authorPrincipal: Principal;
    postId: string;
} {
    return {
        id: value.id,
        likeCount: value.likeCount,
        body: value.body,
        createdAt: value.createdAt,
        parentId: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.parentId)),
        authorPrincipal: value.authorPrincipal,
        postId: value.postId
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    profile: _UserProfile;
}): {
    principal: Principal;
    profile: UserProfile;
} {
    return {
        principal: value.principal,
        profile: from_candid_UserProfile_n17(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    comments: Array<_Comment>;
    posts: Array<_Post>;
}): {
    comments: Array<Comment>;
    posts: Array<Post>;
} {
    return {
        comments: from_candid_vec_n20(_uploadFile, _downloadFile, value.comments),
        posts: value.posts
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaFile>): Array<MediaFile> {
    return value.map((x)=>from_candid_MediaFile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Comment>): Array<Comment> {
    return value.map((x)=>from_candid_Comment_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWithPrincipal>): Array<UserWithPrincipal> {
    return value.map((x)=>from_candid_UserWithPrincipal_n26(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
